sudo: false
language: go
go:
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
  - master
matrix:
  allow_failures:
    - go: master
  fast_finish: true
install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
script:
    - go test -covermode=count -coverprofile=coverage.out -v ./...
    - $HOME/gopath/bin/goveralls -coverage=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
